### ISSUE TITLE
Error when adding instances in a many to many relationship

### ISSUE THREAD

**Issue by cocoabythefire** [wbyoung/azul#8]
I set up a many to many relationship between two models (List and Places) but when I try to add Places to a list using the following code I get an error:

```js
   return list1.addPlaces(placeB);
```

```
Error: Could not find source relation ListPlace#places or ListPlace#place for List#places has-many relation
      at module.exports.Mixin.create._throughRelations (/Users/bntarvin/Code/glitter/node_modules/azul/lib/relations/has_many_through.js:146:17)
      at wrapper [as _throughRelations] (/Users/bntarvin/Code/glitter/node_modules/azul/lib/util/class.js:117:19)
      at module.exports.Mixin.create.inverseIsMany (/Users/bntarvin/Code/glitter/node_modules/azul/lib/relations/has_many_through.js:170:33)
      at null.<anonymous> (/Users/bntarvin/Code/glitter/node_modules/azul/lib/relations/has_many_through.js:20:17)
      at wrapper [as inverseIsMany] (/Users/bntarvin/Code/glitter/node_modules/azul/lib/util/class.js:117:19)
      at null.<anonymous> (/Users/bntarvin/Code/glitter/node_modules/azul/lib/relations/has_many_through.js:40:15)
      at null.<anonymous> (/Users/bntarvin/Code/glitter/node_modules/azul/lib/relations/has_many_through.js:20:17)
      at wrapper [as addObjects] (/Users/bntarvin/Code/glitter/node_modules/azul/lib/util/class.js:117:19)
      at null.<anonymous> (/Users/bntarvin/Code/glitter/node_modules/azul/lib/relations/base.js:430:19)
      at wrapper [as addPlaces] (/Users/bntarvin/Code/glitter/node_modules/azul/lib/util/class.js:117:19)
      at BPromise.resolve.then.then.then.then.then.then.then.then.request.url (/Users/bntarvin/Code/glitter/test/list_place_tests.js:78:37)
      at tryCatcher (/Users/bntarvin/Code/glitter/node_modules/bluebird/js/main/util.js:24:31)
      at Promise._settlePromiseFromHandler (/Users/bntarvin/Code/glitter/node_modules/bluebird/js/main/promise.js:454:31)
      at Promise._settlePromiseAt (/Users/bntarvin/Code/glitter/node_modules/bluebird/js/main/promise.js:530:18)
      at Async._drainQueue (/Users/bntarvin/Code/glitter/node_modules/bluebird/js/main/async.js:137:12)
      at Async._drainQueues (/Users/bntarvin/Code/glitter/node_modules/bluebird/js/main/async.js:142:10)
      at Async.drainQueues (/Users/bntarvin/Code/glitter/node_modules/bluebird/js/main/async.js:16:14)
      at process._tickCallback (node.js:419:13)
```

**Comment by wbyoung** [comment]
@cocoabythefire what do your models (`Place` and `List`) look like?

**Comment by cocoabythefire** [comment]
```js
var Place = db.model('place', {
  lists: db.hasMany({ through: 'list_places' })
});
var List = db.model('list', {
  places: db.hasMany({ through: 'list_places' }),
});
```

**Comment by wbyoung** [comment]
Try adding the following for now and I'll look into this more:

```js
var ListPlace = db.model('list_place', {
  place: db.belongsTo(),
  list: db.belongsTo()
});
```

**Comment by cocoabythefire** [comment]
thanks that fixed it for now.

**Comment by wbyoung** [comment]
Can you check to see if removing that code for the `ListPlace` works when you change your model definition to:

```js
var Place = db.model('place', {
  lists: db.hasMany({ through: 'listPlaces' })
});
var List = db.model('list', {
  places: db.hasMany({ through: 'listPlaces' }),
});
```

Note that the only change is from `list_places` to `listPlaces`.

**Comment by cocoabythefire** [comment]
nope - the error is still there if I use listPlaces

**Comment by wbyoung** [comment]
This was an oversight. Thanks for catching it. You should now be able to do the following in alpha 7 and [the docs have been updated to reflect the change](http://www.azuljs.com/guides/relations/#many-to-many):

```js
var Place = db.model('place', {
  lists: db.hasMany({ join: 'list_places' })
});
var List = db.model('list', {
  places: db.hasMany({ join: 'list_places' }),
});
```

**Comment by cocoabythefire** [comment]
I'm now getting this :(

```
[error: missing FROM-clause entry for table "list_places"]
  cause: 
   { [error: missing FROM-clause entry for table "list_places"]
     name: 'error',
     length: 115,
     severity: 'ERROR',
     code: '42P01',
     detail: undefined,
     hint: undefined,
     position: '30',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_relation.c',
     line: '2615',
     routine: 'errorMissingRTE' },
  length: 115,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '30',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '2615',
  routine: 'errorMissingRTE' }
    1) GET /api/lists/2/places with no places
```

**Comment by wbyoung** [comment]
@cocoabythefire this appears to be a new issue. Can you open a new ticket with the query that you're trying to do and the model setup that you have. I think I've reproduced this, but any clarity in your ticket will certainly help.

**Comment by wbyoung** [comment]
Ok, I think I fixed this in alpha 8. Please open an issue if that's not the case. Sorry for not getting it all in one go.
